package silentorb.imp.parsing.syntax

enum class ParsingMode {
  body,
  definitionAssignment,
  definitionParameterColon,
  definitionParameterNameOrAssignment,
  definitionParameterType,
  definitionName,
  descend,
  expressionRootArgumentStart,
  expressionRootArgumentFollowing,
  expressionRootNamedArgumentValue,
  expressionRootStart,
  importFirstPathToken,
  importFollowingPathToken,
  importSeparator,
  header,
  groupStart,
  groupArgumentStart,
  groupArgumentFollowing,
  groupNamedArgumentValue,
  pipingRootStart,
  pipingGroupedStart,
}
