package silentorb.imp.parsing.general

enum class TextId {

  // Error messages
  ambiguousOverload,
  badArgument,
  circularDependency,
  duplicateSymbol,
  expectedAssignment,
  expectedColon,
  expectedCommaOrAssignment,
  expectedExpression,
  expectedIdentifier,
  expectedIdentifierOrWildcard,
  expectedImportOrLetKeywords,
  expectedLetKeyword,
  expectedNewline,
  expectedParameterName,
  expectedParameterNameOrAssignment,
  expectedPeriodOrNewline,
  importNotFound,
  incompleteParameter,
  invalidToken,
  missingClosingParenthesis,
  missingArgumentName,
  missingArgumentExpression,
  missingExpression,
  missingImportPath,
  multipleGraphOutputs,
  noGraphOutput,
  noMatchingSignature,
  outsideTypeRange,
  unexpectedCharacter,
  unknownFunction,
}
